# Numpy and Pandas

In [159]:
import numpy as np
import pandas as pd

In [160]:
d={1:'a',2:'b',3:'c'}
d1=dict([[2,'e'],[3,'c'],[4,'d']])
d2=dict(zip((4,5,6),('z','f','g')))

In [161]:
d

{1: 'a', 2: 'b', 3: 'c'}

In [162]:
d1

{2: 'e', 3: 'c', 4: 'd'}

In [163]:
d2

{4: 'z', 5: 'f', 6: 'g'}

In [164]:
d1.update(d2)
d.update(d1)

In [165]:
d1

{2: 'e', 3: 'c', 4: 'z', 5: 'f', 6: 'g'}

In [166]:
d2

{4: 'z', 5: 'f', 6: 'g'}

In [167]:
d

{1: 'a', 2: 'e', 3: 'c', 4: 'z', 5: 'f', 6: 'g'}

In [168]:
arr=np.array([[5,9,3],[2,7,1],[4,-3,2]])

In [169]:
arr

array([[ 5,  9,  3],
       [ 2,  7,  1],
       [ 4, -3,  2]])

In [170]:
arr.sort(axis=0)
arr.sort(axis=1)

In [171]:
arr

array([[-3,  1,  2],
       [ 2,  4,  7],
       [ 3,  5,  9]])

In [172]:
arr.sum(axis=0)

array([ 2, 10, 18])

In [173]:
arr1=np.where(arr>4)

In [174]:
arr1

(array([1, 2, 2], dtype=int64), array([2, 1, 2], dtype=int64))

In [175]:
arr.nbytes

36

In [176]:
arr[arr1]

array([7, 5, 9])

In [177]:
from sklearn.datasets import load_diabetes

In [178]:
dataset=load_diabetes()

In [179]:
descr=dataset['DESCR']
descr

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, blood sugar

In [180]:
data=dataset['data']
target=dataset['target']

In [181]:
data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [182]:
target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [187]:
target=target.reshape(-1,1)
data=np.concatenate((data,target),axis=1)
df=pd.DataFrame(data)

In [188]:
df

0         1         2         3         4         5         6    
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401  \
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           7         8         9      10  
0   -0.002592  0.019907 -0.017646  151.0  
1   -0.039493 -0.068332 -0.092204   75.0  
2   -0.002592  0.002861 -0.025930  141.0  
3    0.034309  0.022688 -0.009362  206.0  
4   -0.002592 -0.031988 -0.046641  135.0  
..        ...       ...       ...    ...  
437 -0.002592  0.031193  0.007207  178.0  
438  0.034309 -0.018114  0.044485  104.0  
439 -0.011080 -0.046883  0.015491  132.0  
440  0.026560  0.044529 -0.025930  220.0  
441 -0.039493 -0.004222  0.003064   57.0  

[442 rows x 11 columns]

In [192]:
df.corr()

0         1         2         3         4         5         6    
0   1.000000  0.173737  0.185085  0.335428  0.260061  0.219243 -0.075181  \
1   0.173737  1.000000  0.088161  0.241010  0.035277  0.142637 -0.379090   
2   0.185085  0.088161  1.000000  0.395411  0.249777  0.261170 -0.366811   
3   0.335428  0.241010  0.395411  1.000000  0.242464  0.185548 -0.178762   
4   0.260061  0.035277  0.249777  0.242464  1.000000  0.896663  0.051519   
5   0.219243  0.142637  0.261170  0.185548  0.896663  1.000000 -0.196455   
6  -0.075181 -0.379090 -0.366811 -0.178762  0.051519 -0.196455  1.000000   
7   0.203841  0.332115  0.413807  0.257650  0.542207  0.659817 -0.738493   
8   0.270774  0.149916  0.446157  0.393480  0.515503  0.318357 -0.398577   
9   0.301731  0.208133  0.388680  0.390430  0.325717  0.290600 -0.273697   
10  0.187889  0.043062  0.586450  0.441482  0.212022  0.174054 -0.394789   

          7         8         9         10  
0   0.203841  0.270774  0.301731  0.187889  
1   0.332115  0.149916  0.208133  0.043062  
2   0.413807  0.446157  0.388680  0.586450  
3   0.257650  0.393480  0.390430  0.441482  
4   0.542207  0.515503  0.325717  0.212022  
5   0.659817  0.318357  0.290600  0.174054  
6  -0.738493 -0.398577 -0.273697 -0.394789  
7   1.000000  0.617859  0.417212  0.430453  
8   0.617859  1.000000  0.464669  0.565883  
9   0.417212  0.464669  1.000000  0.382483  
10  0.430453  0.565883  0.382483  1.000000

In [195]:
df1=df.loc[(df[10]>100) & (df[0]<0)]

In [196]:
df1

0         1         2         3         4         5         6    
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038  \
6   -0.045472  0.050680 -0.047163 -0.015999 -0.040096 -0.024800  0.000779   
9   -0.070900 -0.044642  0.039062 -0.033213 -0.012577 -0.034508 -0.024993   
10  -0.096328 -0.044642 -0.083808  0.008101 -0.103389 -0.090561 -0.013948   
15  -0.052738  0.050680 -0.018062  0.080401  0.089244  0.107662 -0.039719   
..        ...       ...       ...       ...       ...       ...       ...   
422 -0.078165  0.050680  0.077863  0.052858  0.078236  0.064447  0.026550   
425 -0.078165 -0.044642 -0.040696 -0.081413 -0.100638 -0.112795  0.022869   
430 -0.009147 -0.044642 -0.056863 -0.050427  0.021822  0.045345 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   

           7         8         9      10  
3    0.034309  0.022688 -0.009362  206.0  
6   -0.039493 -0.062917 -0.038357  138.0  
9   -0.002592  0.067737 -0.013504  310.0  
10  -0.076395 -0.062917 -0.034215  101.0  
15   0.108111  0.036060 -0.042499  171.0  
..        ...       ...       ...    ...  
422 -0.002592  0.040673 -0.009362  233.0  
425 -0.076395 -0.020292 -0.050783  152.0  
430  0.034309 -0.009919 -0.017646  183.0  
438  0.034309 -0.018114  0.044485  104.0  
440  0.026560  0.044529 -0.025930  220.0  

[121 rows x 11 columns]

In [198]:
df.to_csv('Diabetes.csv',index=False)